apiVersion: apps/v1
kind: Deployment
metadata:
  name: relay
spec:
  selector:
    matchLabels:
      app: relay
  template:
    metadata:
      labels:
        app: relay
    spec:
      containers:
        - name: relay
          image: badimage:badtag # This is a placeholder. The image is built and pushed by the CI/CD pipeline.
          ports:
            - containerPort: 2700
          livenessProbe:
            httpGet:
              path: /healthz
              port: 2700
            failureThreshold: 1
            periodSeconds: 5
          startupProbe:
            httpGet:
              path: /healthz
              port: 2700
            failureThreshold: 6
            periodSeconds: 5
          env:
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: postgres-config
                  key: DB_NAME
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-config
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-config
                  key: DB_PASSWORD
            - name: DB_HOST
              value: postgres
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: DB_PORT