apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-persister
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event-persister
  template:
    metadata:
      labels:
        app: event-persister
    spec:
      containers:
        - name: event-persister
          image: badimage:badtag # This is a placeholder. The image is built and pushed by the CI/CD pipeline.
          # livenessProbe:
          #   httpGet:
          #     path: /healthz
          #     port: 2700
          #   failureThreshold: 1
          #   periodSeconds: 5
          # startupProbe:
          #   httpGet:
          #     path: /healthz
          #     port: 2700
          #   failureThreshold: 6
          #   periodSeconds: 5