apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-persister
spec:
  selector:
    matchLabels:
      app: event-persister
  template:
    metadata:
      labels:
        app: event-persister
    spec:
      containers:
        - name: event-persister
          image: event-persister
          ports:
            - containerPort: 2700
          # livenessProbe:
          #   httpGet:
          #     path: /healthz
          #     port: 2700
          #   failureThreshold: 1
          #   periodSeconds: 5
          # startupProbe:
          #   httpGet:
          #     path: /healthz
          #     port: 2700
          #   failureThreshold: 6
          #   periodSeconds: 5
          env:
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: db-config
                  key: DB_NAME
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-config
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-config
                  key: DB_PASSWORD
            - name: DB_HOST
              value: db
            - name: DB_PORT
              value: "3306"
            - name: KAFKA_URL
              value: "kafka.kafka"