apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
 name: letsencrypt-staging
 namespace: cert-manager
spec:
 acme:
   server: https://acme-staging-v02.api.letsencrypt.org/directory
   email: dummyaddress # populated by flux
   privateKeySecretRef:
     name: tls
   solvers:
   - http01:
       ingress:
         class:  nginx