apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: python-ndk-dev
resources:
- ../../base
- secrets.yaml
- self-signed-cluster-issuer.yaml
- ingress.yaml
- db.yaml
patches:
- path: patch-deployment.yaml
  target:
    kind: Deployment
    name: relay