apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: python-ndk-dev
resources:
- ../../base
- service.yaml
- secrets.yaml
- self-signed-cluster-issuer.yaml
patches:
- path: patch-deployment.yaml
  target:
    kind: Deployment
    name: relay
- path: patch-ingress.yaml
  target:
    kind: Ingress
    name: relay-ingress