apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: python-ndk-dev
resources:
- ../../base
- service.yaml
patches:
- path: deployment.yaml
  target:
    kind: Deployment
    name: relay