- op: replace
  path: /spec/template/spec/containers/0/image
  value: python-ndk-relay
- op: add
  path: /spec/template/spec/containers/0/env
  value:
    - name: MODE
      value: KAFKA_PERSISTER
    - name: DB_NAME
      valueFrom:
        secretKeyRef:
          name: db-config
          key: DB_NAME
    - name: DB_USER
      valueFrom:
        secretKeyRef:
          name: db-config
          key: DB_USER
    - name: DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: db-config
          key: DB_PASSWORD
    - name: DB_HOST
      value: postgresql
    - name: KAFKA_URL
      value: kafka.kafka
    - name: RELAY_LOG_LEVEL
      value: DEBUG