- op: replace
  path: /spec/template/spec/containers/0/livenessProbe/periodSeconds
  value: 30
- op: replace
  path: /spec/template/spec/containers/0/image
  value: python-ndk-relay
- op: add
  path: /spec/template/spec/containers/0/env
  value:
    - name: MODE
      value: POSTGRES_KAFKA
    - name: DB_NAME
      valueFrom:
        secretKeyRef:
          name: db-config
          key: DB_NAME
    - name: DB_USER
      valueFrom:
        secretKeyRef:
          name: db-config
          key: DB_USER
    - name: DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: db-config
          key: DB_PASSWORD
    - name: DB_HOST
      value: postgresql
    - name: DROP_DB
      value: "true"
    - name: KAFKA_URL
      value: kafka.kafka
    - name: KAFKA_TOPIC
      value: events
    - name: RELAY_URL
      value: localhost
    - name: RELAY_LOG_LEVEL
      value: DEBUG