apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: self-signed-cluster-issuer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: self-signed-cert
  namespace: python-ndk-dev
spec:
  secretName: self-signed-cert
  issuerRef:
    name: self-signed-cluster-issuer
    kind: ClusterIssuer
  dnsNames:
    - "localhost"
    - "nostr.com.se"
    - "*.nostr.com.se"