name: Pre-commit Checks

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  ci:
    name: Unit & Integration Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
      fail-fast: false
    env:
      COVPYTEST: "coverage run -m pytest"

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies [dev]
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          poetry self update 1.4.0
          poetry install --extras dev

      - name: Formatting / Linting Checks
        run: |
          poetry run lint
    
      - name: NDK Unit Tests
        env:
          COVERAGE_FILE: .coverage.unit.ndk${{ matrix.python-version }}
        run: |
          poetry run ${{ env.COVPYTEST }} ndk

      - name: NDK Relay Unit Tests
        env:
          COVERAGE_FILE: .coverage.unit.relay.${{ matrix.python-version }}
        run: |
          poetry run ${{ env.COVPYTEST }} relay

      - name: Functional Tests against In-Memory Relay
        env:
          COVERAGE_FILE: .coverage.functional.in-memory${{ matrix.python-version }}
        run: |
          poetry run pip install coverage
          poetry run ${{ env.COVPYTEST }} functional_tests

      - name: Spec Tests against In-Memory Relay
        env:
          COVERAGE_FILE: .coverage.spec.in-memory${{ matrix.python-version }}
        run: |
          poetry run pip install coverage
          poetry run ${{ env.COVPYTEST }} spec_tests

      - name: Install dependencies [cli]
        run: |
          poetry install --extras cli

      - name: Sanity Tests
        run: |
          poetry run python scripts/nostrcli_sanity_check.py

      - name: Upload Partial Coverage Results
        uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: .coverage.*

      - name: Build ndk package
        run: |
          poetry build

      - name: Upload ndk package
        uses: actions/upload-artifact@v3
        with:
          name: ndk
          path: dist/*.whl

  server_tests:
    name: Functional & Spec tests against server built with NDK
    needs: [ci]
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      INGRESS_HOST: "localhost"
      INGRESS_PORT: "8443"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Download ndk package
        uses: actions/download-artifact@v3
        with:
          name: ndk
          path: /tmp/ndk/

      - name: Install dependencies
        run: |
          pip install /tmp/ndk/$(ls /tmp/ndk/)[test] coverage
          sudo wget -qO /usr/local/bin/websocat https://github.com/vi/websocat/releases/latest/download/websocat.x86_64-unknown-linux-musl
          sudo chmod a+x /usr/local/bin/websocat

      - name: Install Tilt
        run: curl -fsSL https://raw.githubusercontent.com/tilt-dev/tilt/master/scripts/install.sh | bash

      - name: Start minikube
        id: minikube
        uses: medyagh/setup-minikube@master

      - name: Start Tilt
        run: |
          minikube addons enable ingress
          tilt up --stream -f relay/deploy/Tiltfile > /tmp/server.log 2>&1 &

      - name: Wait for Traefik to come up
        run: |
          while [[ $(kubectl get pods -n traefik --selector "app.kubernetes.io/name=traefik" -o jsonpath="{range .items[*]}{@.status.conditions[?(@.type=='Ready')].status}") != "True" ]]; do echo "waiting for traefik pod" && sleep 1; done
          kubectl port-forward $(kubectl get pods -n traefik --selector "app.kubernetes.io/name=traefik" --output=name) 8443:8443 -n traefik &

      - name: Wait for Relay to start
        run: |
          while [[ $(kubectl get pods --namespace python-ndk-dev -l app=relay -o jsonpath="{range .items[*]}{@.status.conditions[?(@.type=='Ready')].status}") != "True" ]]; do echo "waiting for relay pod" && sleep 1; done
          kubectl wait --for=condition=Available --timeout=300s -n cert-manager deployment/cert-manager
          kubectl wait --for=condition=Available --timeout=300s -n cert-manager deployment/cert-manager-cainjector
          kubectl wait --for=condition=Available --timeout=300s -n cert-manager deployment/cert-manager-webhook

      - name: Wait for websocket to open
        run: |
          for i in {1..60}; do websocat --insecure wss://${{ env.INGRESS_HOST }}:${{ env.INGRESS_PORT }} && break || echo "Retrying in 1s..." && sleep 1; done

      - name: Run Functional Tests
        env:
          COVERAGE_FILE: .coverage.functional.ndk-server-minikube
        run: coverage run -m pytest --timeout=10 functional_tests --relay-url=wss://${{ env.INGRESS_HOST }}:${{ env.INGRESS_PORT }}

      - name: Run Spec Tests
        env:
          COVERAGE_FILE: .coverage.spec.ndk-server-minikube
        run: coverage run -m pytest --timeout=10 spec_tests --relay-url=wss://${{ env.INGRESS_HOST }}:${{ env.INGRESS_PORT }}

      - name: Dump Server Logs
        if: always()
        run: cat /tmp/server.log

      - name: Upload Partial Coverage Results
        uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: .coverage.*

  upload_code_coverage:
    name: Upload Code Coverage
    runs-on: ubuntu-latest
    needs: [ci, server_tests]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Download Code Coverage
        uses: actions/download-artifact@v3
        with:
          name: coverage

      - name: List downloaded coverage files
        run: ls -la

      - name: Create codecov report
        run: |
          pip install coverage
          coverage combine
          coverage xml
      
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}  

  publish:
    name: Publish docker image
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: [ci, server_tests]
    env:
      IMAGE: "registry.digitalocean.com/python-ndk/python-ndk-relay"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DigitalOcean Registry
        uses: docker/login-action@v2
        with:
          registry: registry.digitalocean.com
          username: ${{ secrets.DIGITAL_OCEAN_TOKEN }}
          password: ${{ secrets.DIGITAL_OCEAN_TOKEN }}

      - name: Set up build Env Variables
        id: prep
        run: |
          BRANCH=${GITHUB_REF##*/}
          TS=$(date +%s)
          REVISION=${GITHUB_SHA::8}
          BUILD_ID="${BRANCH}-${REVISION}-${TS}"
          LATEST_ID=canary
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            BUILD_ID=${GITHUB_REF/refs\/tags\//}
            LATEST_ID=latest
          fi
          echo "BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_ENV
          echo "BUILD_ID=${BUILD_ID}" >> $GITHUB_ENV
          echo "LATEST_ID=${LATEST_ID}" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: relay/deploy/relay.dockerfile
          platforms: linux/amd64
          push: true
          build-args: "RELAY_EVENT_REPO=mysql"
          tags: |
            ${{ env.IMAGE }}:${{ env.BUILD_ID }}
            ${{ env.IMAGE }}:${{ env.LATEST_ID }}