name: Pre-commit Checks

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  ci:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
      fail-fast: false
    env:
      COVPYTEST: "coverage run -m pytest"

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies [dev]
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          poetry self update 1.4.0
          poetry install --extras dev

      - name: Formatting / Linting Checks
        run: |
          poetry run lint
    
      - name: Unit Tests
        env:
          COVERAGE_FILE: .coverage.unit
        run: |
          poetry run ${{ env.COVPYTEST }} ndk

      - name: Install dependencies [test]
        run: |
          poetry install --extras test

      - name: Functional Tests
        env:
          COVERAGE_FILE: .coverage.functional
        run: |
          poetry run pip install coverage
          poetry run ${{ env.COVPYTEST }} functional_tests

      - name: Install dependencies [cli]
        run: |
          poetry install --extras cli

      - name: Sanity Tests
        run: |
          poetry run python scripts/nostrcli_sanity_check.py

      - name: Create codecov report
        run: |
          poetry run pip install coverage
          poetry run coverage combine
          poetry run coverage xml

      - name: Upload coverage reports to Codecov
        if: matrix.python-version == '3.10' # only upload this once
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Build
        run: |
          poetry build